### ISSUE TITLE
underground laser field error

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#160]
placing a laserfield in a undergound style causes the following error

Checking Conditions...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 2782, in main
  File "F:\Git\BEE2.4\src\conditions.py", line 433, in check_all
  File "F:\Git\BEE2.4\src\conditions.py", line 297, in test
  File "F:\Git\BEE2.4\src\conditions.py", line 286, in test_result
  File "F:\Git\BEE2.4\src\conditions.py", line 344, in <lambda>
  File "F:\Git\BEE2.4\src\vbsp.py", line 676, in find_panel_locs
TypeError: argument of type 'NoneType' is not iterable

**Comment by ellingtonisland** [comment]
confirmed fixed for next release - case closed
