### ISSUE TITLE
pack list compile error in prerelease 15

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#200]
this comes up upon compile within all styles, didn't have the sentificator in PTI when this happened either. i think prerelease 15 is the most buggy version yet. no test chambers or styles compile!

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3045, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 2819, in make_packlist
  File "F:\Git\BEE2.4\src\property_parser.py", line 222, in parse
property_parser.KeyValError: Extra text after line: "models/hmw/props/sendificator.mdl"
Error occured on line 13, with file "bee2/pack_list.cfg"
```

**Comment by TeamSpen210** [comment]
I've uploaded a fixed version of the packages (pr 15.1).

**Comment by Tomidlo158** [comment]
I am getting error when I am extracting these packages.What should I do?

**Comment by ellingtonvengaboysmuseum** [comment]
fixed with package update, case closed
