### ISSUE TITLE
placing a flame thrower in 60's style causes the following

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#214]
placing a flame thrower in 60's style causes the following

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3150, in main
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 465, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 329, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 318, in test_result
  File "F:\Git\BEE2.4\src\vbsp.py", line 1982, in cond_force_clump
ValueError: too many values to unpack (expected 3)
```

**Comment by CrashingScience** [comment]
they dont have and in editor texture either

**Comment by ellingtonvengaboysmuseum** [comment]
fixed for next release - case closed
