### ISSUE TITLE
bug: compiling a default  portal 1 test chamber causes the following

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#264]
compiling a default portal 1 test chamber causes the following in pre release 17

```
[I] instanceLocs: --------
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\instanceLocs.py", line 243, in resolve
ValueError: invalid literal for int() with base 10: 'bee2_entry_door'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3150, in main
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 465, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 329, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 318, in test_result
  File "F:\Git\BEE2.4\src\conditions\addInstance.py", line 81, in res_add_overlay_inst
  File "c:\python\32-bit\3.4\lib\functools.py", line 458, in wrapper
  File "F:\Git\BEE2.4\src\instanceLocs.py", line 253, in resolve
Exception: "bee2_entry_door" is not a valid instance subtype or index!
```

**Comment by BenVlodgi** [comment]
This error happens in the python code, the bug would be better reported under the BEE2.4 issues

**Comment by TeamSpen210** [comment]
This should be fixed now.
