### ISSUE TITLE
overgrown compile error 

### ISSUE THREAD

**Issue by ellingtonisland** [TeamSpen210/BEE2-items#36]
i get this when i try to create a simple overgrown test with no items in the new bee2.4 pre release 5

Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198025151093\1435588171.p2c
Ellington Isle unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 78 (ms)

VBSP failed.

Config "../config\config.cfg" not found! Using defaults...
Adding metacondition ("remove_blank_inst") with priority 1000!
Adding metacondition ("fix_catapult_targets") with priority 0!
Adding metacondition ("add_voice") with priority 100!
Adding metacondition ("fix_fizz_models") with priority -200!
Adding metacondition ("static_pan") with priority -100!
Adding metacondition ("anti_fizz_bump") with priority 200!
BEE2 VBSP hook initiallised.
Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
Loading settings...
Failed parsing weight! ([])
Failed parsing weight! ([])
{}
Settings Loaded!
PeTI map detected!
Parsing Map...
Parsing complete!
1 1 1
Game Mode: SP
Is Preview: True
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 1765, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 619, in get_map_info
AttributeError: 'NoneType' object has no attribute 'x'

**Comment by ellingtonisland** [comment]
fixed
