### ISSUE TITLE
bug: MAJOR compile error - pre-release 20 is BROKEN!

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [TeamSpen210/BEE2-items#509]
i get this error in ALL styles in pre-release 20 with no items and compiling a default test chamber.

<b>Pre-release 20 is broken!!</b>

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3852, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 3449, in make_packlist
  File "F:\Git\BEE2.4\src\property_parser.py", line 278, in parse
  File "F:\Git\BEE2.4\src\property_parser.py", line 150, in read_flag
property_parser.KeyValError: Extra text after line: "models/props/light_rail_corner.dx90.vtx"
Error occured on line 10, with file "bee2/pack_list.cfg"

**Comment by TeamSpen210** [comment]
This should be fixed now with the pr20.5 packages.
