### ISSUE TITLE
[Prl21.5 Bug] Grating causes "Failure to compile" (Log included)

### ISSUE THREAD

**Issue by LautaroL20** [TeamSpen210/BEE2-items#613]
Lautaro unpaused the game
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 82 (ms)
[PORTAL2 PUZZLEMAKER]  Saved puzzle: E:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198046602127\autosave.p2c

VBSP failed.

[I] vbsp: BEE VBSP hook initiallised.
[I] cond.core: Imported all conditions modules!
[I] vbsp: Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp: New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp: Clearing inject/ directory..
[I] vbsp: PeTI map detected!
[I] vbsp: Loading settings...
[W] instanceLocs: None in vals: False
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Failed parsing weight! ([])
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[W] cond.core: Invalid weight! ()
[I] vbsp: Settings Loaded!
[I] vbsp: Parsing Map...
[I] vbsp: Reading Map...
[I] vbsp: Loading complete!
[I] vbsp: Forcing elevator spawn!
[I] vbsp: Setting SP Entry to 1
[I] vbsp: Setting SP Exit to 1
[I] vbsp: Game Mode: SP
[I] vbsp: Is Preview: False
[I] brushLoc: Analysed map, filling air... (95 starting positions..)
[I] brushLoc: Air filled!
[I] cond.core: Checking Conditions...
[I] cond.core: GooDebris: 0/0 locations
[I] cond.catwalks: Starting catwalk generator...
[I] cond.scaffold: Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold: Finished Scaffold generation!
[I] cond.vactubes: Running Generator (BEE2_VACTUBES)...
[I] vbsp: Elevator type: RAND
[I] voiceLine: Adding Voice Lines!
[I] voiceLine: Adding Base instance!
[I] voiceLine: Quote events: []
[I] voiceLine: No responses data..
[I] voiceLine: Adding quote: "Line_SP"
 | 	{
 | 	"ID" "ENTRY_GEN_TECH_DIFF"
 | 	"File" "ann_apoc/entry_tech_diff.vmf"
 | 	}
 |_

[I] voiceLine: Adding quote: "Line"
 | 	{
 | 	"ID" "EXIT_GEN_EVAC"
 | 	"Choreo" "npc/announcer/evacuationmisc01.vcd"
 | 	}
 |_

[I] voiceLine: End-commands: 
[I] voiceLine: 0 Mid quotes
[I] voiceLine: Done!
[I] vbsp: Setting Portalgun:
[I] vbsp: Blue: Y, Orange: Y
[I] vbsp: Done!
[I] vbsp: Added Screenshot Logic
[I] cond.core: Map has attributes: ['spawn_dual']
[I] cond.core: instanceLocs cache: CacheInfo(hits=16857, misses=296, maxsize=256, currsize=256)
[I] cond.core: Style Vars: {'nomidvoices': False, 'rexcubepelletfizzle': False, 'bee2_goo_debris': True, 'allowgoomist': True, 'fixfizzlerbump': False, 'bee_show_trigger': True, 'multiversecave': False, 'unlockdefault': False}
[I] cond.core: Global instances: {'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf'}
[I] vbsp: Adding Music...
[I] vbsp: Adding Global PTI Ents
[I] vbsp: Editing Other Entities...
[I] vbsp: Changing goo sides...
[I] vbsp: Done!
[I] vbsp: Editing Brushes...
[I] vbsp: Make Bottomless Pit: False
[I] vbsp: Adding Goo Mist...
[I] vbsp: Done!
[I] vbsp: Editing Overlays...
[I] vbsp: Editing Triggers...
[I] vbsp: Collapsing goo triggers...
[I] vbsp: Done!
[I] vbsp: Editing Brush Entities...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "vbsp_launch.py", line 7, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 3594, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 2818, in change_func_brush
UnboundLocalError: local variable 'brush_key' referenced before assignment

**Comment by LautaroL20** [comment]
This also happens on all the styles by using the zip fix.
