### ISSUE TITLE
Crash when saving backups

### ISSUE THREAD

**Issue by cartman1337** [TeamSpen210/BEE2-items#833]
This is a bug of Bee2.exe, not linked to any game item or style. When you go to the Backup/Restore Puzzles option from the File menu, and choose either "Save Backup" or ".. As", when you hit Save on whatever file name and location you choose, the program crashes with an error saying:

BEE2 Error:
ZeroDivisionError: ZeroDivisionError('division by zero',)

In other words, backup isn't working, because no file is created.

**Comment by TheDarkBomber** [comment]
Seems like a Python error where it is trying to divide something by zero.

**Comment by cartman1337** [comment]
Ah, sorry. I'll do that.

**Comment by TeamSpen210** [comment]
Post the end of the BEE2/logs/BEE2.log file here.

**Comment by cartman1337** [comment]
```
[INFO] backup.load_backup(): Done!
[ERROR] tk_tools.tk_error(): TKinter callback exception occurred:
 | Traceback (most recent call last):
 |   File "F:\Git\BEE2.4\src\backup.py", line 622, in ui_save_backup_as
 |   File "F:\Git\BEE2.4\src\backup.py", line 605, in ui_save_backup
 |   File "F:\Git\BEE2.4\src\backup.py", line 447, in save_backup
 |   File "F:\Git\BEE2.4\src\loadScreen.py", line 146, in set_length
 |   File "F:\Git\BEE2.4\src\loadScreen.py", line 157, in set_nums
 | ZeroDivisionError: division by zero
 |_


```

**Comment by TeamSpen210** [comment]
You need to chlose some maps to backup first. I need to add a better error message than crashing, though.

**Comment by cartman1337** [comment]
I did choose files to backup. I chose all the files in this instance. Here's a few more lines from the log:

```
[INFO] backup.load_backup(): Loading 21 maps..
[DEBUG] backup.load_backup(): Loading sp map "The Two Towers"
[DEBUG] backup.load_backup(): Loading sp map "The Two Towers"
[DEBUG] backup.load_backup(): Loading sp map "Test 2"
[DEBUG] backup.load_backup(): Loading sp map "Death Row Turret Executioner"
[DEBUG] backup.load_backup(): Loading sp map "Prison Break"
[DEBUG] backup.load_backup(): Loading sp map "Tetris Tower"
[DEBUG] backup.load_backup(): Loading sp map "Locked Tower"
[DEBUG] backup.load_backup(): Loading sp map "Travelling In Circles"
[DEBUG] backup.load_backup(): Loading sp map "Test"
[DEBUG] backup.load_backup(): Loading sp map "Forgotten Chamber"
[DEBUG] backup.load_backup(): Loading sp map "The Cube, the Gel and the Panels"
[DEBUG] backup.load_backup(): Loading sp map "Silo"
[DEBUG] backup.load_backup(): Loading sp map "Nakatomi Plaza"
[DEBUG] backup.load_backup(): Loading sp map "Send Me Home In Time"
[DEBUG] backup.load_backup(): Loading sp map "Sendificator"
[DEBUG] backup.load_backup(): Loading sp map "Sphere test"
[DEBUG] backup.load_backup(): Loading sp map "The Sendificator Test Factory"
[DEBUG] backup.load_backup(): Loading sp map "BTS Exit test"
[DEBUG] backup.load_backup(): Loading sp map "Wall and Window Test"
[DEBUG] backup.load_backup(): Loading sp map "1"
[DEBUG] backup.load_backup(): Loading sp map "Sendificator"
[INFO] backup.load_backup(): Done!
[ERROR] tk_tools.tk_error(): TKinter callback exception occurred:
 | Traceback (most recent call last):
 |   File "F:\Git\BEE2.4\src\backup.py", line 622, in ui_save_backup_as
 |   File "F:\Git\BEE2.4\src\backup.py", line 605, in ui_save_backup
 |   File "F:\Git\BEE2.4\src\backup.py", line 447, in save_backup
 |   File "F:\Git\BEE2.4\src\loadScreen.py", line 146, in set_length
 |   File "F:\Git\BEE2.4\src\loadScreen.py", line 157, in set_nums
 | ZeroDivisionError: division by zero
 |_


```

**Comment by TeamSpen210** [comment]
Were the maps on the left hand list?

**Comment by cartman1337** [comment]
No, they are on the right hand side, under the "PORTAL 2" header. The left hand side is empty.

**Comment by TeamSpen210** [comment]
That's the problem then. The way the backup program works is that the right side is the contents of the game, the left is the contents of the backup. You can use the buttons under it to copy files around, then save the backup via the file menu.

**Comment by cartman1337** [comment]
Not quite intuitive, though. It should leave a more descriptive error message when trying to do it the other way too.

**Comment by TeamSpen210** [comment]
That's done now.
